listener {
	timeout = 180
	on-timeout = "hyprsunset -g 70"
	on-resume = "hyprsunset -g 100"
}

listener {
	timeout = 300
	on-timeout = "blazinlock -i /home/javi/.wallpaper/Nordic-mountain-wallpaper.jpg"
}
